//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DebitControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Computer()
        {
            this.DebitComputer = new HashSet<DebitComputer>();
        }
    
        public short computerId { get; set; }
        public string computerBrand { get; set; }
        public string computerModel { get; set; }
        public string computerName { get; set; }
        public string computerSerialNumber { get; set; }
        public string computerLanMac { get; set; }
        public string computerWifiMac { get; set; }
        public string computerWin { get; set; }
        public string computerOffice { get; set; }
        public short computerNumber { get; set; }
        public bool computerUsbStatus { get; set; }
        public bool computerStatus { get; set; }
        public Nullable<short> licenceId { get; set; }
    
        public virtual License License { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DebitComputer> DebitComputer { get; set; }
    }
}
