//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DebitControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DebitDevice
    {
        public short debitDeviceId { get; set; }
        public System.DateTime debitDeviceStartdate { get; set; }
        public Nullable<System.DateTime> debitDeviceFinishdate { get; set; }
        public bool debitDeviceStatus { get; set; }
        public Nullable<short> employeeId { get; set; }
        public Nullable<short> deviceId { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
