//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DebitControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DebitComputer
    {
        public short debitComputerId { get; set; }
        public System.DateTime debitComputerStartdate { get; set; }
        public Nullable<System.DateTime> debitComputerFinishdate { get; set; }
        public Nullable<short> employeeId { get; set; }
        public Nullable<short> computerId { get; set; }
        public bool debitComputerStatus { get; set; }
    
        public virtual Computer Computer { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
