//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DebitControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Device()
        {
            this.DebitDevice = new HashSet<DebitDevice>();
        }
    
        public short deviceId { get; set; }
        public string deviceType { get; set; }
        public string deviceBrand { get; set; }
        public string deviceModel { get; set; }
        public string deviceSerialNumber { get; set; }
        public short deviceNumber { get; set; }
        public bool deviceStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DebitDevice> DebitDevice { get; set; }
    }
}
